import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import "react-toastify/dist/ReactToastify.css";
import { ToastContainer } from "react-toastify";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "piano-caffee",
  description: "Generated by create next app",
};

import localFont from "next/font/local";

const vazirmatn = localFont({
  src: [
    {
      path: "../fonts/vazirmatn/Vazirmatn-Regular.woff2",
      weight: "400",
    },
    {
      path: "../fonts/vazirmatn/Vazirmatn-Medium.woff2",
      weight: "500",
    },
    {
      path: "../fonts/vazirmatn/Vazirmatn-Bold.woff2",
      weight: "700",
    },
  ],
  display: "swap",
});


export default function RootLayout({ children }) {
  return (
    <html
      lang="fa"
      dir="rtl"
      className={`${vazirmatn.className} h-full antialiased`}
    >
      <body className="min-h-full flex flex-col">
        {children}
        <ToastContainer
          position="top-center"
          autoClose={2500}
          hideProgressBar
          closeOnClick
          pauseOnHover
          draggable
          theme="dark"
          toastClassName="!bg-[#0f0f0f]/90 !backdrop-blur-md !text-white !rounded-2xl !shadow-2xl !border !border-white/10"
          bodyClassName="!text-sm sm:!text-base !font-medium"
          className="!w-[92vw] sm:!w-auto"
        />
      </body>
    </html>
  );
}
